### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by didoarellano** [leemalmac/frodo#1]
Any plans on publishing to npm? Then installation can be a simple `npm install -g frodo`.

**Comment by nodari-l** [comment]
Hi Dido.
Yes. I'll try to make it in a couple days.
Did not expected that this tool would be wanted)

**Comment by amingilani** [comment]
@leemalmac oh it is, it really is!

**Comment by nodari-l** [comment]
Published https://www.npmjs.com/package/frodojs
